name: "Build payload"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Build with PS4 Payload SDK
        uses: Scene-Collective/ps4-payload-sdk@main
        with:
          app_path: .
          build_command: make
      - name: Upload payload artifact
        uses: actions/upload-artifact@main
        with:
          name: "app.bin"
          path: "app.bin"
